apiVersion: apps/v1
kind: Deployment
metadata:
  name: target-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      role: target-demo
  template:
    metadata:
      labels:
        role: target-demo
    spec:
      containers:
        - name: target-demo
          image: paam0101/target-demo:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/products_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "user"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "password"
